name: cloudstate
version: 0.5.1
description: A Cloudstate Dart Language Support.
homepage: https://cloudstate.io
repository: https://github.com/sleipnir/cloudstate-dart-support.git

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  async: ^2.2.0
  optional: ^4.1.0
  grpc: ^2.1.3
  protobuf: ^1.0.1
  googleapis_auth: ^0.2.7
  meta: ^1.1.6
  http: ^0.12.0
  http2: ^1.0.0
  logger: ^0.8.3
  yaml: ^2.2.0
  fixnum: ^0.10.11

dev_dependencies:
  pedantic: ^1.8.0
  build_runner: ^1.5.2
  build_test: ^0.10.8
  mockito: ^4.1.0
  test: ^1.6.4
